apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-configmap-reload1
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload1
    spec:
      containers:
        - name: kubernetes-configmap-reload1
          image: praveensingam1994/kubernetes-configmap-reload:latest
